import { Project, Activity, User } from './types';

export const mockUsers: User[] = [
    { id: '1', name: 'Admin User', role: 'admin' },
    { id: '2', name: 'Owner', role: 'owner' },
    { id: '3', name: 'Country Manager TR', role: 'country_manager', assignedLocationId: 'TR' },
    { id: '4', name: 'Country Manager DE', role: 'country_manager', assignedLocationId: 'DE' },
    { id: '5', name: 'Country Manager US', role: 'country_manager', assignedLocationId: 'US' },
    { id: '6', name: 'Region Manager Marmara', role: 'region_manager', assignedLocationId: 'Marmara' },
    { id: '7', name: 'City Manager Istanbul', role: 'city_manager', assignedLocationId: 'Istanbul' },
    { id: '8', name: 'Site Manager S-001', role: 'site_manager', assignedLocationId: 'S-001' },
];

export const mockProjects: Project[] = [
    {
        id: 'P-100',
        name: 'Istanbul Financial Center',
        location: 'Turkey, Istanbul',
        country: 'Turkey',
        region: 'Marmara',
        city: 'Istanbul',
        siteId: 'S-001',
        status: 'in_progress',
        budget: 50000000,
        startDate: '2025-01-01',
        endDate: '2027-12-31',
        progress: 35,
    },
    {
        id: 'P-101',
        name: 'Ankara Tech Hub',
        location: 'Turkey, Ankara',
        country: 'Turkey',
        region: 'Central Anatolia',
        city: 'Ankara',
        siteId: 'S-002',
        status: 'planning',
        budget: 25000000,
        startDate: '2026-06-01',
        endDate: '2028-06-01',
        progress: 0,
    },
    {
        id: 'P-102',
        name: 'Izmir Port Expansion',
        location: 'Turkey, Izmir',
        country: 'Turkey',
        region: 'Aegean',
        city: 'Izmir',
        siteId: 'S-003',
        status: 'delayed',
        budget: 150000000,
        startDate: '2024-03-01',
        endDate: '2029-03-01',
        progress: 15,
    },
    {
        id: 'P-103',
        name: 'Berlin Central Station Renovation',
        location: 'Germany, Berlin',
        country: 'Germany',
        region: 'Berlin',
        city: 'Berlin',
        siteId: 'S-DE-01',
        status: 'in_progress',
        budget: 85000000,
        startDate: '2025-05-15',
        endDate: '2028-11-30',
        progress: 45,
    },
    {
        id: 'P-104',
        name: 'Munich Airport Terminal 3',
        location: 'Germany, Munich',
        country: 'Germany',
        region: 'Bavaria',
        city: 'Munich',
        siteId: 'S-DE-02',
        status: 'planning',
        budget: 320000000,
        startDate: '2027-01-10',
        endDate: '2032-12-31',
        progress: 0,
    },
    {
        id: 'P-105',
        name: 'New York Hudson Yards Extension',
        location: 'United States of America, New York',
        country: 'United States of America',
        region: 'New York',
        city: 'New York',
        siteId: 'S-US-01',
        status: 'in_progress',
        budget: 1500000000,
        startDate: '2024-01-01',
        endDate: '2030-12-31',
        progress: 60,
    },
    {
        id: 'P-106',
        name: 'London Crossrail 2',
        location: 'United Kingdom, London',
        country: 'United Kingdom',
        region: 'Greater London',
        city: 'London',
        siteId: 'S-UK-01',
        status: 'planning',
        budget: 5000000000,
        startDate: '2030-01-01',
        endDate: '2040-12-31',
        progress: 0,
    },
    {
        id: 'P-107',
        name: 'Paris Olympic Village Conversion',
        location: 'France, Paris',
        country: 'France',
        region: 'Île-de-France',
        city: 'Paris',
        siteId: 'S-FR-01',
        status: 'in_progress',
        budget: 120000000,
        startDate: '2024-09-01',
        endDate: '2026-12-31',
        progress: 20,
    },
    {
        id: 'P-108',
        name: 'Tokyo Bay Bridge Maintenance',
        location: 'Japan, Tokyo',
        country: 'Japan',
        region: 'Kanto',
        city: 'Tokyo',
        siteId: 'S-JP-01',
        status: 'completed',
        budget: 45000000,
        startDate: '2023-01-01',
        endDate: '2025-01-01',
        progress: 100,
    },
    {
        id: 'P-109',
        name: 'Sydney Metro Expansion',
        location: 'Australia, Sydney',
        country: 'Australia',
        region: 'New South Wales',
        city: 'Sydney',
        siteId: 'S-AU-02',
        status: 'in_progress',
        budget: 250000000,
        startDate: '2023-05-01',
        endDate: '2026-12-01',
        progress: 40
    },
    {
        id: 'P-110',
        name: 'Toronto Pearson Terminal Revamp',
        location: 'Canada, Toronto',
        country: 'Canada',
        region: 'Ontario',
        city: 'Toronto',
        siteId: 'S-CA-02',
        status: 'delayed',
        budget: 180000000,
        startDate: '2022-09-15',
        endDate: '2025-03-30',
        progress: 60
    }
];

export const mockActivities: Activity[] = [
    { id: 'ACT-001', projectId: 'P-100', name: 'Site Preparation', status: 'completed', startDate: '2025-01-01', endDate: '2025-02-15', predecessors: [], successors: ['ACT-002'] },
    { id: 'ACT-002', projectId: 'P-100', name: 'Foundation Work', status: 'active', startDate: '2025-02-16', endDate: '2025-06-30', predecessors: ['ACT-001'], successors: ['ACT-003', 'ACT-004'] },
    { id: 'ACT-003', projectId: 'P-100', name: 'Structural Framing', status: 'pending', startDate: '2025-07-01', endDate: '2025-12-31', predecessors: ['ACT-002'], successors: ['ACT-005'] },
    { id: 'ACT-004', projectId: 'P-100', name: 'Plumbing & Electrical Rough-in', status: 'pending', startDate: '2025-08-01', endDate: '2026-01-31', predecessors: ['ACT-002'], successors: ['ACT-005'] },
    { id: 'ACT-005', projectId: 'P-100', name: 'Interior Finishing', status: 'pending', startDate: '2026-02-01', endDate: '2026-10-31', predecessors: ['ACT-003', 'ACT-004'], successors: ['ACT-006'] },
    { id: 'ACT-006', projectId: 'P-100', name: 'Final Inspection', status: 'pending', startDate: '2026-11-01', endDate: '2026-12-15', predecessors: ['ACT-005'], successors: [] },

    { id: 'ACT-010', projectId: 'P-101', name: 'Feasibility Study', status: 'completed', startDate: '2025-10-01', endDate: '2025-12-31', predecessors: [], successors: ['ACT-011'] },
    { id: 'ACT-011', projectId: 'P-101', name: 'Architectural Design', status: 'active', startDate: '2026-01-01', endDate: '2026-05-31', predecessors: ['ACT-010'], successors: [] },
];
